<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>ccbb4858-e204-4ee8-b36f-c8dd9e1730c3</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\blog-keycloak-series.Domain\blog-keycloak-series.Domain.csproj" />
        <ProjectReference Include="..\blog-keycloak-series.ServiceDefaults\blog-keycloak-series.ServiceDefaults.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.1.0-preview.1.25616.3" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

</Project>
